### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by LongDirtyAnimAlf** [STMicroelectronics/x-cube-tcpp#4]
Hello,
I noticed that the copyright notice in many files has changed from 2021 to 2018.
E.g. : https://github.com/STMicroelectronics/x-cube-tcpp/blob/1f8d2dcca862d06e8c6307be34308909380f5b32/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/src/usbpd_timersserver.c#L9
I am worried that this also means that the sources itself are from 2018. Containing old buggers.
Can you please shed some light on this issue ?
Thanks.

**Comment by HFISTM** [comment]
Hello,

Thank you for your question.

I understand that this is unclear. Our copyright policy was recently updated and this repository has been updated to reflect it in the newest release. The copyright year stated in the file header now corresponds to the official MCU year, which is 2018 for STM32G0. 

If you want to know the file version, and ensure it is up to date, please refer to its release note: https://github.com/STMicroelectronics/x-cube-tcpp/blob/main/Middlewares/ST/STM32_USBPD_Library/Devices/STM32G0XX/Release_Notes.html

The file you pointed is from the USBPD G0 device driver package, which is up to date in version v3.4.0 / 13-December-2021. This is the version released in the latest x-cube-tcpp release V3.2.0, and I can confirm you that it is the most up to date source for this driver package as of today.

Best regards.
